1   # Generated by Django 5.1.5 on 2025-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=50)),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
    ]
